[project]
name = 'escrow-service'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-oracle]
path = 'contracts/reputation-oracle.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
